version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

sphinx:
  configuration: doc/sphinx/conf.py
  fail_on_warning: true

python:
  install:
  - requirements: doc/sphinx/requirements.txt
